In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv",header=None)

In [3]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,112,113,114,115,116,117,118,119,120,121
0,69769,-946,0.1613,0.7960,Panl,N,Bus2,0.0742,0,2,...,1.0,-4670,0.9851,0.0,0,Mard,0.0,0.3333,0,0
1,236977,-92,NaN,NaN,NaN,Y,Othr,NaN,0,3,...,NaN,-1994,NaN,NaN,0,Mard,0.0,NaN,0,0
2,168821,-1646,0.1124,0.8504,Panl,N,Bus3,0.0387,0,2,...,2.0,-2842,0.9891,0.0,0,Sind,0.0,0.3750,0,1
3,94708,-1651,0.0263,NaN,Blok,N,Bus3,NaN,0,2,...,4.0,-1345,0.9682,0.0,0,Sind,0.0,0.0417,0,1
4,84556,-977,NaN,NaN,NaN,N,Rest,NaN,0,2,...,NaN,-852,NaN,NaN,0,Sind,0.0,NaN,0,0

In [4]:
df.isnull().sum().sum()

7318445

In [5]:
df.shape

(246008, 122)

In [6]:
df.columns[df.isnull().any()]

Int64Index([  2,   3,   4,   7,  10,  11,  12,  13,  14,  16,  17,  18,  21,
             22,  25,  27,  32,  34,  35,  36,  38,  39,  40,  43,  44,  45,
             48,  49,  51,  54,  56,  58,  59,  60,  61,  68,  72,  74,  77,
             78,  79,  80,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
             92,  95,  96,  99, 101, 102, 107, 109, 110, 111, 112, 114, 115,
            118, 119],
           dtype='int64')

In [7]:
nulls=[]
for col in df.columns:
    if df[col].isnull().sum() > 30000:
        nulls.append(col)
print(nulls)

[2, 3, 4, 7, 10, 11, 12, 14, 17, 18, 21, 22, 32, 34, 36, 38, 39, 43, 44, 45, 48, 49, 51, 54, 56, 58, 59, 60, 61, 68, 74, 77, 78, 79, 80, 82, 83, 84, 86, 87, 88, 89, 90, 91, 92, 95, 96, 101, 102, 107, 109, 110, 111, 112, 114, 115, 119]

In [8]:
len(nulls)

57

In [9]:
df=df.drop(columns=nulls)

In [10]:
df.isna().sum()

0        0
1        0
5        0
6        0
8        0
      ...
116      0
117      0
118    811
120      0
121      0
Length: 65, dtype: int64

In [11]:
df.isna().sum().sum()

5038

In [12]:
df

,0,1,5,6,8,9,13,15,16,19,...,104,105,106,108,113,116,117,118,120,121
0,69769,-946,N,Bus2,0,2,180000.0,0,Unad,0,...,1,0,0,0,-4670,0,Mard,0.0,0,0
1,236977,-92,Y,Othr,0,3,135000.0,0,Unad,0,...,1,0,0,0,-1994,0,Mard,0.0,0,0
2,168821,-1646,N,Bus3,0,2,553500.0,0,Spor,0,...,1,0,0,0,-2842,0,Sind,0.0,0,1
3,94708,-1651,N,Bus3,0,2,391500.0,0,Unad,0,...,1,0,0,0,-1345,0,Sind,0.0,0,1
4,84556,-977,N,Rest,0,2,225000.0,0,Unad,0,...,1,0,0,0,-852,0,Sind,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246003,248161,-595,N,Bus3,0,2,405000.0,0,Unad,0,...,1,0,0,0,-4420,0,Mard,0.0,0,0
246004,257069,-4334,N,Mede,0,2,225000.0,0,Unad,0,...,1,0,0,0,-2561,0,Sind,0.0,0,0
246005,154350,365243,N,XNAA,0,2,234000.0,0,Unad,0,...,0,0,0,0,-4636,0,Cive,0.0,0,0
246006,148183,365243,N,XNAA,0,3,810000.0,0,Chin,0,...,0,0,0,0,-4636,0,Mard,0.0,0,1
246007,5167,365243,Y,XNAA,0,2,877500.0,0,Famy,0,...,0,0,0,0,-4266,0,Mard,0.0,0,0

In [13]:
df.dtypes

0        int64
1        int64
5       object
6       object
8        int64
        ...
116      int64
117     object
118    float64
120      int64
121      int64
Length: 65, dtype: object